
# -*- mode: ruby -*-
# vi: set ft=ruby :
#


Vagrant.configure('2') do |config|

  config.vm.define 'fun-with-c-vagrant-box' do |s|
    s.vm.box = 'debian/contrib-stretch64'
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 4
  end
  config.vm.synced_folder '../c-things', '/home/vagrant/c-things'
  config.vm.synced_folder '../cpp-stuff', '/home/vagrant/cpp-stuff'
  config.vm.provision :file, source: 'files/tmux.conf', destination: '/home/vagrant/.tmux.conf'

  # install some packages
  config.vm.provision :shell, inline: <<-SHELL
    apt-get update
    apt-get install vim git tmux gcc gdb -y
  SHELL

end
